# Personalize your website info here
title:            Daniela Saderi
tagline:          'Professional Website for Daniela Saderi'
description:      'Website and Blog for Daniela Saderi'
url:              http://dasaderi.github.io
author:
  name:           'Daniela Sadeir'
  url:            https://twitter.com/Neurosarda

## You don't need to modify below this line
paginate:         5

# Custom vars
version:          2.1.0
github:
  repo:           https://github.com/poole/hyde

gems: [jekyll-paginate,jekyll-gist, redcarpet]
paginate: 5
paginate_path: "page:num"

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
baseurl:          /
